#!/bin/bash
# Manual SSH Command Guide
# Copy and paste these commands one by one after connecting via SSH

echo "=========================================="
echo "PRIME OPS WEB SERVER RESTART COMMANDS"
echo "=========================================="
echo ""
echo "First, connect to the server:"
echo "  ssh root@31.97.228.226"
echo ""
echo "Then run these commands one by one:"
echo ""
echo "# 1. Check current PM2 status"
echo "pm2 list"
echo ""
echo "# 2. Stop the current process"
echo "pm2 stop prime.client 2>/dev/null || echo 'Not running'"
echo ""
echo "# 3. Delete the process"
echo "pm2 delete prime.client 2>/dev/null || echo 'Not found'"
echo ""
echo "# 4. Kill any stray processes on port 5173"
echo "pkill -9 -f 'serve.*5173' 2>/dev/null || echo 'No stray processes'"
echo "lsof -ti:5173 | xargs kill -9 2>/dev/null || echo 'Port is free'"
echo ""
echo "# 5. Navigate to project directory"
echo "cd /var/lib/jenkins/workspace/prime-ops-web || cd /root/prime-ops-web"
echo ""
echo "# 6. Verify you're in the right directory"
echo "pwd"
echo "ls -la dist/ | head -5"
echo ""
echo "# 7. Start the service with PM2"
echo "pm2 start npx --name prime.client -- serve -s dist -l 5173"
echo ""
echo "# 8. Save PM2 configuration"
echo "pm2 save"
echo ""
echo "# 9. Verify the service is running"
echo "pm2 list"
echo "lsof -i:5173"
echo ""
echo "# 10. Test locally on the server"
echo "curl -I http://localhost:5173"
echo ""
echo "=========================================="
echo "If successful, the site should be accessible at:"
echo "http://31.97.228.226:5173"
echo "=========================================="
